# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
default_stages: ["commit"]
repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.0.0.9046
    hooks: 
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: readme-rmd-rendered
    -   id: deps-in-desc
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
        exclude: '^tests/testthat/.*/*\.R'
    -   id: roxygenize # spell-check needs up-to date doc.
    -   id: spell-check
        exclude: >
          (?x)^(
          data/.*| 
          (.*/|)\.Rprofile|
          (.*/|)\.Renviron|
          (.*/|)\.gitignore|
          (.*/|)NAMESPACE|
          (.*/|)WORDLIST|
          (.*/|)\.travis.yml|
          (.*/|)appveyor.yml|
          (.*/|)\.Rbuildignore|
          (.*/|)\.pre-commit-.*|
          .*\.[rR]|
          .*\.Rproj|
          .*\.py|
          .*\.feather|
          .*\.rds|
          .*\.Rds|
          .*\.sh|
          .*\.RData
          )$
    -   id: use-tidy-description
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks: 
    -   id: check-added-large-files
    -   id: end-of-file-fixer
        exclude: '\.Rd' # sometimes roxygen fails to generate EOF blank line.
-   repo: local
    hooks:
    -   id: consistent-release-tag
        name: consistent-release-tag
        entry: inst/consistent-release-tag
        language: script
        stages: [commit, push]
    -   id: hooks-config-to-inst
        name: hooks-config-to-inst
        entry: inst/hooks-config-to-inst
        language: script
        stages: [commit, push]
    -   id: spell-check-exclude-to-config
        name: spell-check-exclude-to-config
        entry: inst/spell-check-exclude-to-config
        language: script
        stages: [commit, push]
    -   id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .Rdata, .csv and similar.
        language: fail
        files: '\.Rhistory|\.csv|\.RData|\.Rds|\.rds$'
        # `exclude: <regex>` to allow committing specific files.
